### ISSUE TITLE
Could you add containers from unordered-containers?

### ISSUE THREAD

**Issue by kozross** [mstksg/nonempty-containers#6]
I recently found myself in need of the equivalent of ``Data.HashSet.NonEmpty``, but this doesn't exist in this package. Could you add it?

**Comment by mstksg** [comment]
Hm, I would daresay that this might potentially be outside the scope of this package.  It feels a bit cleaner to have this be only containers, and another package would handle unordered-containers, since I had the intention of making this a tightly coupled thing, with the API of this library identically mirroring containers.

That being said I would consider a PR, but also might suggest the effort in a PR be put into publishing a competing package :)

**Comment by kozross** [comment]
Well, _if_ you insist, I can certainly do that.

**Comment by mstksg** [comment]
The seeds of the koziverse are growing :)
